spring.application.name=wommilkmgmt
# ===============================
# DATABASE CONFIGURATION
# ===============================
server.address=0.0.0.0
spring.datasource.url=jdbc:postgresql://66.116.227.31:5432/milkmgmt
spring.datasource.username=postgres
spring.datasource.password=milkmgmt
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SERVER
# ===============================

server.port=8080
app.jwt.secret=K7gNU3sdo+OL0wNhqoVWhr3g6s1xYv72ol/pe/Unols=
app.jwt.expiration-ms=31536000000